title: longtds's blog
description: longtds's blog. linux devops container kubernetes cloudnative hadoop

url: https://longtds.github.io
baseurl: "/"
paginate_path: "page:num/"
permalink: :title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 9

navigation:
  - title: Home
    url: /index.html
#  - title: About
#    url: /about
#  - title: Contact
#    url: /contact

social:
  github: longtds
  twitter: longtds
  facebook: longtds
  email: longtds@163.com
  linkedin: longtds

google_analytics: "UA-180658907-1"

disqus:
    shortname: longtds
